# 图形验证码有效期，单位：秒
IMAGE_CODE_REDIS_EXPIRES = 300

# 短信验证码有效期，单位：秒
SMS_CODE_REDIS_EXPIRES = 300

# 短信模板
SEND_SMS_TEMPLATE_ID = 1

# 60s内是否重复发送的标记
SEND_SMS_CODE_INTERVAL = 60

# 记住登录的状态保持时间
REMEMBERED_EXPIRES = 3600

# openid过期时间
OPENID_EXPIRES = 600

# 邮件验证链接有效期：一天
VERIFY_EMAIL_TOKEN_EXPIRES = 60 * 60 * 24

# 用户地址上限
USER_ADDRESS_COUNTS_LIMIT = 20

# 省市区联动数据缓存过期时间
PROVINCE_CITY_DISTRICT_EXPIRES = 3600

# 商品列表页每页显示记录的条数
RECORDS_NUM_PER_PAGE = 5

# 个人中心显示浏览记录的条数
USER_CENTER_HISTORY_COUNT = 5

