# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-01-29 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goodschannelgroup_time_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodschannelgroup',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
